logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.sunglowsys: DEBUG

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atithih
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect